apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  nodeSelector:
    nome: worker1
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-site
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-site
      hostPath:
        path: /dados/nginx-site
        type: DirectoryOrCreate
