apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.15.200
    path: "/dados/volnfs"
  mountOptions:
    - nfsvers=4.2
