apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date
            image: busybox
            name: my-cronjob
          restartPolicy: OnFailure
  schedule: "*/1 * * * *"
