apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: pod-list-binding
subjects:
- kind: ServiceAccount
  name: my-serviceaccount
  namespace: my-namespace
roleRef: 
  kind: Role
  name: pod-list-role
