apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-list-role
  namespace: my-namespace
rules:
  - apiGroups: [""]
    resources: ["pods","services"]
    verbs: ["get", "watch", "list","create","delete"]

