apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:1.21
    - name: backup-container
      image: alpine:3.14
      command: ["sh", "-c", "while true; do echo 'Realizando backup...'; sleep 3600; done"]

