apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    env: dev    
spec:
  nodeSelector:
    kubernetes.io/hostname: worker2.asf.com     
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
   
