apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
 MYSQL_ROOT_PASSWORD: TGludXhGb3JjZTAx
 MYSQL_USER: bXl1c2Vy
 MYSQL_PASSWORD: TGludXhGb3JjZTAx
 MYSQL_DATABASE: bXlkYXRhYmFzZQ== 
