apiVersion: v1
kind: Pod
metadata:
   name: mysql-pod3
spec:
  containers: 
    - name: mysql-container
      image: mysql:latest
      envFrom:
        - secretRef:
            name: mysql-secret
      ports:
        - containerPort: 3306     
