apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql-container
    image: mysql:latest
    envFrom:
      - configMapRef:
          name: mysql-config     
    ports:
    - containerPort: 3306
